# Site settings
title: Byron Han Blog
SEOTitle: Byron Han 的博客 | Byron Han Blog
header-img: img/post-bg-desk.jpg
email: postmaster@hanjl.com
description: "Every failure is leading towards success."
keyword: "Byron Han的博客, Byron Han, 韩京磊 ,hanjinglei,hjl , HANJINGLEI"
url: "http://hanjl7.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/hanjl7/hanjl7.github.io.git" # you code repository

# SNS settings
RSS: false
weibo_username:     5221893152
zhihu_username:     hanjinglei
github_username:    hanjl7

#twitter_username: xx
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: byronhan

# Gitalk
# gitalk:
  #   enable: true    #是否开启Gitalk评论
  #  clientID: fed163f8ed8f3197cb96                           #生成的clientID
  #  clientSecret: 1ed6d8a4420479fe2bc8c897b41fb3a7170f2ddb    #生成的clientSecret
  #  repo: resume    #仓库名称
  #   owner: hanjl7    #github用户名
  #   admin: hanjl7
  #  distractionFreeMode: true #是否启用类似FB的阴影遮罩

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
ba_track_id: aca626ea8725d70913a35aebcda3bea2

# Google Analytics
ga_track_id: 'UA-133450563-2'            # Format: UA-xxxxxx-xx
ga_domain: blog.hanjl.com              # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "你好，世界！"
sidebar-avatar: https://github.com/hanjl7.png # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 4 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends: [
    {
        title: "QQ音乐歌单",
        href: "http://url.cn/5fpeA3f"
    },{
        title: "2018年流派新歌，歌曲分为R&B、民谣、电子、说唱、新世纪等类型，均为这些编辑口味，较为主观的推荐，希望你能够喜欢",
        href: "http://url.cn/50k2b8u"
    },{
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]


